[tools]
sqlite = "latest"
uv = "latest"
node = "latest"

[tasks.status]
run = "uv run panic-tda experiment-status"

[tasks.script]
run = "uv run panic-tda script"

[tasks.charts]
run = "uv run panic-tda paper-charts"

[tasks.test]
run = "uv run pytest -n auto \"${@}\""

[tasks.list-experiments]
run = "uv run panic-tda list-experiments"
