[tools]
sqlite = "latest"
uv = "latest"

[tasks.status]
run = "uv run trajectory-tracer experiment-status"

[tasks.script]
run = "uv run trajectory-tracer script"

[tasks.test]
run = "uv run pytest"

[tasks.delete]
run = "uv run trajectory-tracer delete-experiment ${@}"
