[tools]
sqlite = "latest"
uv = "latest"
node = "latest"
bun = "latest"

[tasks.script]
run = "uv run panic-tda script"

[tasks.charts]
run = "uv run panic-tda export charts"

[tasks.test]
run = "uv run pytest -n 8"

[tasks.tda]
run = "uv run panic-tda"
