[tools]
sqlite = "latest"
uv = "latest"

[tasks.status]
run = "uv run trajectory-tracer experiment-status"

[tasks.script]
run = "uv run trajectory-tracer script"

[tasks.charts]
run = "uv run trajectory-tracer paper-charts"

[tasks.test]
run = "uv run pytest"

[tasks.list-experiments]
run = "uv run trajectory-tracer list-experiments"
