[project]
name = "trajectory-tracer"
version = "0.1.0"
description = "A package to collect traces of different AI trajectories under different initial conditions"
readme = "README.md"
requires-python = "~=3.12.0"
dependencies = [
    "accelerate>=1.4.0",
    "diffusers>=0.32.2",
    "einops>=0.8.1",
    "giotto-ph>=0.2.4",
    "persim>=0.3.7",
    "piexif>=1.1.3",
    "pillow>=11.1.0",
    "protobuf>=6.30.0",
    "pydantic>=2.10.6",
    "pytest>=8.3.5",
    "pyvips>=2.2.3",
    "rich>=13.9.4",
    "sentence-transformers>=3.4.1",
    "sentencepiece>=0.2.0",
    "sqlmodel>=0.0.23",
    "timm>=1.0.15",
    "torch>=2.6.0",
    "torchvision>=0.21.0",
    "transformers>=4.49.0",
    "uuid-v7>=1.0.0",
]

[tool.pytest.ini_options]
pythonpath = ["."]
markers = ["slow: marks tests as slow (deselect with '-m \"not slow\"')"]
addopts = "-m 'not slow'"

[dependency-groups]
dev = ["pytest>=8.3.5"]

[tool.ruff.format]
# Enable preview style formatting.
preview = true
