defmodule PanicTda.Repo.Migrations.InitialSetup do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:runs, primary_key: false) do
      add :experiment_id,
          references(:experiments, column: :id, name: "runs_experiment_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :initial_prompt, :text, null: false
      add :max_length, :bigint, null: false
      add :seed, :bigint, null: false
      add :network, {:array, :text}, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:persistence_diagrams, primary_key: false) do
      add :run_id,
          references(:runs, column: :id, name: "persistence_diagrams_run_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :completed_at, :utc_datetime_usec
      add :started_at, :utc_datetime_usec, null: false
      add :diagram_data, :binary
      add :embedding_model, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:persistence_diagrams, [:run_id, :embedding_model],
             name: "persistence_diagrams_unique_run_model_index"
           )

    create table(:invocations, primary_key: false) do
      add :input_invocation_id,
          references(:invocations,
            column: :id,
            name: "invocations_input_invocation_id_fkey",
            type: :uuid
          )

      add :run_id, references(:runs, column: :id, name: "invocations_run_id_fkey", type: :uuid),
        null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :completed_at, :utc_datetime_usec
      add :started_at, :utc_datetime_usec, null: false
      add :output_image, :binary
      add :output_text, :text
      add :sequence_number, :bigint, null: false
      add :seed, :bigint, null: false
      add :type, :text, null: false
      add :model, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:experiments, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :completed_at, :utc_datetime_usec
      add :started_at, :utc_datetime_usec
      add :max_length, :bigint, null: false
      add :embedding_models, {:array, :text}, null: false
      add :prompts, {:array, :text}, null: false
      add :seeds, {:array, :bigint}, null: false
      add :networks, {:array, {:array, :text}}, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:embeddings, primary_key: false) do
      add :invocation_id,
          references(:invocations,
            column: :id,
            name: "embeddings_invocation_id_fkey",
            type: :uuid
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :completed_at, :utc_datetime_usec
      add :started_at, :utc_datetime_usec, null: false
      add :vector, :binary, null: false
      add :embedding_model, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:embeddings, [:invocation_id, :embedding_model],
             name: "embeddings_unique_invocation_model_index"
           )

    create table(:embedding_clusters, primary_key: false) do
      add :medoid_embedding_id,
          references(:embeddings,
            column: :id,
            name: "embedding_clusters_medoid_embedding_id_fkey",
            type: :uuid
          )

      add :clustering_result_id,
          references(:clustering_results,
            column: :id,
            name: "embedding_clusters_clustering_result_id_fkey",
            type: :uuid
          ), null: false

      add :embedding_id,
          references(:embeddings,
            column: :id,
            name: "embedding_clusters_embedding_id_fkey",
            type: :uuid
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:clustering_results, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :completed_at, :utc_datetime_usec
      add :started_at, :utc_datetime_usec, null: false
      add :parameters, :map, default: %{}
      add :algorithm, :text, null: false
      add :embedding_model, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:embedding_clusters, [:embedding_id, :clustering_result_id],
             name: "embedding_clusters_unique_embedding_clustering_index"
           )
  end

  def down do
    drop_if_exists unique_index(:embedding_clusters, [:embedding_id, :clustering_result_id],
                     name: "embedding_clusters_unique_embedding_clustering_index"
                   )

    drop table(:clustering_results)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `embedding_clusters` table without the `embedding_clusters_embedding_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `embedding_clusters` table without the `embedding_clusters_clustering_result_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `embedding_clusters` table without the `embedding_clusters_medoid_embedding_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:embedding_clusters)

    drop_if_exists unique_index(:embeddings, [:invocation_id, :embedding_model],
                     name: "embeddings_unique_invocation_model_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `embeddings` table without the `embeddings_invocation_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:embeddings)

    drop table(:experiments)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `invocations` table without the `invocations_run_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `invocations` table without the `invocations_input_invocation_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:invocations)

    drop_if_exists unique_index(:persistence_diagrams, [:run_id, :embedding_model],
                     name: "persistence_diagrams_unique_run_model_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `persistence_diagrams` table without the `persistence_diagrams_run_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:persistence_diagrams)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `runs` table without the `runs_experiment_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:runs)
  end
end