defmodule PanicTda.Repo.Migrations.AddI2tMaxNewTokens do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:experiments) do
      add :i2t_max_new_tokens, :bigint
    end
  end

  def down do
    alter table(:experiments) do
      remove :i2t_max_new_tokens
    end
  end
end