defmodule PanicTda.Repo.Migrations.AddClusteringLayer do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:clustering_results) do
      add :layer, :bigint, null: false, default: 0
    end

    create unique_index(
             :clustering_results,
             [:experiment_id, :embedding_model, :algorithm, :layer],
             name: "clustering_results_unique_layer_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :clustering_results,
                     [:experiment_id, :embedding_model, :algorithm, :layer],
                     name: "clustering_results_unique_layer_index"
                   )

    alter table(:clustering_results) do
      remove :layer
    end
  end
end