defmodule PanicTda.Repo.Migrations.AddValidationsAndIdentities do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:runs, [:experiment_id, :seed, :initial_prompt],
             name: "runs_unique_experiment_run_index"
           )

    create unique_index(:invocations, [:run_id, :sequence_number],
             name: "invocations_unique_run_sequence_index"
           )

    alter table(:clustering_results) do
      add :experiment_id,
          references(:experiments,
            column: :id,
            name: "clustering_results_experiment_id_fkey",
            type: :uuid
          ), null: false
    end
  end

  def down do
    alter table(:clustering_results) do
      remove :experiment_id
    end

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `clustering_results` table without the `clustering_results_experiment_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop_if_exists unique_index(:invocations, [:run_id, :sequence_number],
                     name: "invocations_unique_run_sequence_index"
                   )

    drop_if_exists unique_index(:runs, [:experiment_id, :seed, :initial_prompt],
                     name: "runs_unique_experiment_run_index"
                   )
  end
end