defmodule PanicTda.Repo.Migrations.AddCastIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:runs, ["CAST(experiment_id AS TEXT)"], name: "runs_experiment_id_text_index")

    create index(:runs, ["CAST(id AS TEXT)"], name: "runs_id_text_index")

    create index(:persistence_diagrams, ["CAST(run_id AS TEXT)", "embedding_model"],
             name: "persistence_diagrams_run_id_text_index"
           )

    create index(:persistence_diagrams, ["CAST(id AS TEXT)"],
             name: "persistence_diagrams_id_text_index"
           )

    create index(:invocations, ["CAST(run_id AS TEXT)", "sequence_number"],
             name: "invocations_run_id_text_index"
           )

    create index(:invocations, ["CAST(id AS TEXT)"], name: "invocations_id_text_index")

    create index(:experiments, ["CAST(id AS TEXT)"], name: "experiments_id_text_index")

    create index(:embeddings, ["CAST(invocation_id AS TEXT)", "embedding_model"],
             name: "embeddings_invocation_id_text_index"
           )

    create index(:embeddings, ["CAST(id AS TEXT)"], name: "embeddings_id_text_index")

    create index(:embedding_clusters, ["CAST(clustering_result_id AS TEXT)"],
             name: "embedding_clusters_clustering_result_id_text_index"
           )

    create index(:embedding_clusters, ["CAST(embedding_id AS TEXT)"],
             name: "embedding_clusters_embedding_id_text_index"
           )

    create index(:embedding_clusters, ["CAST(id AS TEXT)"],
             name: "embedding_clusters_id_text_index"
           )

    create index(:clustering_results, ["CAST(id AS TEXT)"],
             name: "clustering_results_id_text_index"
           )
  end

  def down do
    drop_if_exists index(:clustering_results, ["CAST(id AS TEXT)"],
                     name: "clustering_results_id_text_index"
                   )

    drop_if_exists index(:embedding_clusters, ["CAST(id AS TEXT)"],
                     name: "embedding_clusters_id_text_index"
                   )

    drop_if_exists index(:embedding_clusters, ["CAST(embedding_id AS TEXT)"],
                     name: "embedding_clusters_embedding_id_text_index"
                   )

    drop_if_exists index(:embedding_clusters, ["CAST(clustering_result_id AS TEXT)"],
                     name: "embedding_clusters_clustering_result_id_text_index"
                   )

    drop_if_exists index(:embeddings, ["CAST(id AS TEXT)"], name: "embeddings_id_text_index")

    drop_if_exists index(:embeddings, ["CAST(invocation_id AS TEXT)", "embedding_model"],
                     name: "embeddings_invocation_id_text_index"
                   )

    drop_if_exists index(:experiments, ["CAST(id AS TEXT)"], name: "experiments_id_text_index")

    drop_if_exists index(:invocations, ["CAST(id AS TEXT)"], name: "invocations_id_text_index")

    drop_if_exists index(:invocations, ["CAST(run_id AS TEXT)", "sequence_number"],
                     name: "invocations_run_id_text_index"
                   )

    drop_if_exists index(:persistence_diagrams, ["CAST(id AS TEXT)"],
                     name: "persistence_diagrams_id_text_index"
                   )

    drop_if_exists index(:persistence_diagrams, ["CAST(run_id AS TEXT)", "embedding_model"],
                     name: "persistence_diagrams_run_id_text_index"
                   )

    drop_if_exists index(:runs, ["CAST(id AS TEXT)"], name: "runs_id_text_index")

    drop_if_exists index(:runs, ["CAST(experiment_id AS TEXT)"],
                     name: "runs_experiment_id_text_index"
                   )
  end
end